### PR TITLE
remove '?' it caused the web server to not start

### PR DESCRIPTION
**Pull request by Zaid-maker**
Error with `?` on startup below:
Screenshot 2021-05-21 203838

Without `?` below:
Screenshot 2021-05-21 203647

### CODE REVIEW

**Comment by Sank6** [comment]
No, that's optional chaining. Update your node version

**Comment by Zaid-maker** [comment]
BRUH

**Comment by Zaid-maker** [comment]
its nodejs v12

**Comment by Sank6** [comment]
LTS is v14.

**Comment by Zaid-maker** [comment]
wym?

**Pull request closed without merging**
