### PR TITLE
Fix Bug Unknown Error when member not in main server

### PR DESCRIPTION
**Pull request by shootdot**
#330

### CODE REVIEW

**Comment by Sank6** [comment]
That wouldn't work because the member won't be in thr cache if they only just joined. You'd have to `.fetch()`

**Comment by shootdot** [comment]
Hmm Yeah.

**Comment by shootdot** [comment]
Maybe this should work.

**Comment by shootdot** [comment]
@Sank6 The above code works. Try it.

**Comment by Sank6** [comment]
It looks like it should work. You can delete the variable `memberCheck` though. It isn't used anywhere, so don't bother storing it. Just fetching the member should result in an error if the user isn't in the server.

**Comment by shootdot** [comment]
Yea I will delete right away and update it.

**Pull request merged**
