### PR TITLE
Add Bot Tags/Categories

### PR DESCRIPTION
**Pull request by shootdot**
Necessary Changes are made. Sank6 Please review it.

### CODE REVIEW

**Comment by shootdot** [comment]
image
Sank6 I am not hat good in CSS please edit it. Preview ^^

**Comment by Sank6** [comment]
Yeah sure that's fine. Make sure you use loops instead of actually typing out each and every bot tag.

**Comment by shootdot** [comment]
Of-course Loops exist for some reason 😂😂

```
            each tag in tags
                a.atag(href=`/tag/${tag}` style='margin:8px;') #{tag}
```

I have a doubt. Tags should be customizable ? Like owner should import tags in config.json ?
If it's that how do I make express.js for those things 🤔?

**Comment by Sank6** [comment]
Yeah make it customisable. Have an array with the list of tags. Store the bot tags in an array, so the schema type as an array. And then add a checking step in the backend to check the tags the user has added are part of the list of all possible tags.

**Comment by Sank6** [comment]
And you don't need a separate endpoint for the tags. Make it part of the bot edit router.

**Comment by shootdot** [comment]
Hmm ty for help i will work on it once I'm on PC 😊

**Comment by shootdot** [comment]
So here is a list of thing I'm making in Bot Tags/Categories :- 

1. Tags can be customizable. You can insert tags needed for your bot list in `config.json` file.
2. The tags can be choosen from dropdown menu and selected tags cannot be seen again in dropdown menu. So it does not check in backend and reduce submission time.
3. Maximum 6 Tags (Default) can be choose by a user. You can change how much ever tags can be choosen by user in `config.json`


Is this okay ?

**Comment by Sank6** [comment]
That looks good, but how is your dropdown going to work? Is it going to be a dropdown of checkboxes?
Also, in the `form.js` (frontend), I think it makes more sense if you filter out the checkboxes that are ticked and only send those. There's no point hiding selected ones.

**Comment by shootdot** [comment]
It's not like checkboxes. It will show a dropdown menu and you choose from there and once you choose an option that option is not visible again in dropdown menu. And once it reaches the limit (example 6 tags) It won't show the dropdown menu again unless any tags are removed. Got it ?

**Comment by shootdot** [comment]
Dude @Sank6 in `src/routes/api/like/index.js` Edit `like` to `likes` in line 14

**Comment by Sank6** [comment]
@shootdot ty. fixed.

**Comment by shootdot** [comment]
Np.

**Comment by DavePlayzz** [comment]
Do this Work on https://glitch.com/   ?

**Comment by Zaid-maker** [comment]
I am hype to see that update.

**Comment by shootdot** [comment]
Stay tuned @Zaid-maker

**Comment by Sank6** [comment]
@DavePlayzz No, read the setup wiki.

**Comment by shootdot** [comment]
@Sank6 Except routes everything is made. By the way I'm stuck in making routes.  How do I make it ?

**Comment by Sank6** [comment]
Don't add any routes. It's part of the bot edit page right? Just send the details in the form.js and check it in the backend.

**Comment by shootdot** [comment]
I have already updated form.js. check it.

**Comment by shootdot** [comment]
And how it is a part of bot edit page ? I was making something like this when a user click specific tag in any botinfo page it shows all the bots related to that tag.

**Comment by shootdot** [comment]
@Sank6 Changes are done test it 👍

**Comment by shootdot** [comment]
@Sank6 When will you review this ?

**Comment by Sank6** [comment]
I'll look through them later today. I couldn't yesterday because of the conflicts.

**Comment by shootdot** [comment]
Oh Okay Sure 👍

>

**Pull request merged**
