### PR TITLE
added a website link githubrepo and support server

### PR DESCRIPTION
**Pull request by Duui3111**

### CODE REVIEW

**Comment by Duui3111** [comment]
thee is for the botinfo cmd 
```js
    async run(message, [user]) {
        if (!user || !user.bot) return message.channel.send(`Ping a **bot** to get info about.`);
        if (user.id === message.client.user.id) return message.channel.send(`-_- No`);

        const bot = await Bots.findOne({ botid: user.id }, { _id: false })
        if (!bot) return message.channel.send(`Bot not found.`)
        let e = new MessageEmbed()
            .setColor(0x6b83aa)
            .setAuthor(bot.username, bot.logo, bot.invite)
            .setDescription(bot.description)
            .addField(`Prefix`, bot.prefix ? bot.prefix : "Unknown", true)
            .addField(`Owner`, `<@${bot.owners[0]}>`, true)
            .addField(`State`, bot.state, true)
            .addField(`bot Website`, bot.Website ? bot.Website : "not provided", true)
            .addField(`support Server`,bot.supportServer ? bot.supportServer : "not provided ", true)
            .addField(`Github Repo`,bot.GithubRepo ? bot.GithubRepo : "not provided ", true)
        message.channel.send(e);
    }
```

**Comment by Sank6** [comment]
I can't actually see what's changed. You seem to have replaced every line of every file?  Any way you can only commit changes?

**Comment by ririko5834** [comment]
Please commit only changes if you can. @Duui3111

**Comment by ririko5834** [comment]
Why was this closed?

**Comment by Sank6** [comment]
I already commented. If he makes another PR with the correct commits, i can review them.

**Comment by ririko5834** [comment]
@Duui3111 Please 🙏  commit only changes

**Comment by discord-bot-purchases** [comment]
@Duui3111 can't even do it anymore, he dont know pug

**Comment by ririko5834** [comment]
:/ Its so sad

**Comment by Sank6** [comment]
?? He didn't add it properly in the first place. It's been two weeks. Also, [docs](https://jade-lang.com/).

**Pull request closed without merging**
