### PR TITLE
Add Fields [Support Server, Website, Github Repo] & Fix Typo

### PR DESCRIPTION
**Pull request by shootdot**

### CODE REVIEW

**Comment by ririko5834** [comment]
Does this 100% work?

**Comment by shootdot** [comment]
@ririko5834 Yes It works. You can try it and check if any bugs report here.

**Comment by ririko5834** [comment]
OK, (sorry for asking) are you working on certified bots or bot categories or admin panel?

**Comment by shootdot** [comment]
Working on Bot Categories and Certification system

**Comment by shootdot** [comment]
image

**Comment by ririko5834** [comment]
ty, you are great contributor ❤️

**Comment by Sank6** [comment]
Again, I don't think certified is necessary. Bot categories is good though. 👍

**Comment by shootdot** [comment]
Oh. Do u like the field of Bot Tags ?

**Comment by Sank6** [comment]
@shootdot the idea is good, but the style of the layout doesn't really match the rest of the page. Honestly though, I think just put the bot tags in the config file and as long as it works, it's good. I can change the styling afterwards. I'll look through the code for this pr in a bit.

**Comment by wolfier74** [comment]
When this will be in master branch? It seems that here are not included bot categorie/tags

**Comment by Sank6** [comment]
This PR was just for the extra fields. I'll merge to master soon. Development is just me checking that it works and fixing other things.

**Comment by wolfier74** [comment]
Ok, @shootdot Can you make pr also for this?
And maybe you should add config.json option to setup your own tags for your botlist.

> image
> 😪

**Comment by shootdot** [comment]
I have opened PR #335  I'm still working on it.

**Pull request merged**
