### PR TITLE
Check if User Liked API

### PR DESCRIPTION
**Pull request by shootdot**

### CODE REVIEW

**Comment by Sank6** [comment]
I think it would be more useful to have an API endpoint for "which users have liked this bot" and then setup a ratelimit.

**Comment by shootdot** [comment]
> I think it would be more useful to have an API endpoint for "which users have liked this bot" and then setup a ratelimit.

So need of authorization ? Also my Hard work RIP 😭

**Comment by shootdot** [comment]
The API endpoint will be `http://localhost/api/auth/liked?botid=BOTID?userid=USERID` ?

**Comment by Sank6** [comment]
Nono, you still need the authorisation. Most of your code will be the same. It's more just: `Users.find({ liked: botid })`.
And then filter for likes in the past 12 hours.

**Comment by shootdot** [comment]
Oh got it...

**Comment by shootdot** [comment]
@Sank6 Update Done.

**Comment by ririko5834** [comment]
When it will be in master?

**Comment by Sank6** [comment]
I still need to add mark as nsfw to it and then test for bugs as well.

**Comment by ririko5834** [comment]
Ok, also can you add that when declining bot from dashboard, bot checker can choose reason from list by number or write custom ,like when using command

**Comment by shootdot** [comment]
> Ok, also can you add that when declining bot from dashboard, bot checker can choose reason from list by number or write custom ,like when using command

You can already mention the he reason for declining the bot why do you need a list for it ? Tbh It's useless.

**Comment by Sank6** [comment]
Yeah it's not necessary but having a few default options would be useful if you're declining many bots for the same reasons. Instead if typing it out each time, you could just select one. It wouldn't look very clean though inside a swal.

**Pull request merged**
