### PR TITLE
Give reason why bot was removed

### PR DESCRIPTION
**Pull request by idk-pixel**

### CODE REVIEW

**Comment by Zaid-maker** [comment]
Please provide image so we can see how it looks thanks

**Comment by Sank6** [comment]
Instead of `Reason: {REASON}`, can you change it to a new line and add the reason in a quote with the `>`. Otherwise, looks good.

**Comment by idk-pixel** [comment]
mk

**Comment by idk-pixel** [comment]
#288 Sorry

**Comment by Sank6** [comment]
Just clone your fork and commit to this patch branch. Your new pr doesn't work. It sends to the message channel, not the owners' DMs.

**Comment by idk-pixel** [comment]
@Sank6 FIXED!

**Pull request merged**
