### PR TITLE
Added Custom scroll bar

### PR DESCRIPTION
**Pull request by Awish-Senpai**
custom scroll bar

### CODE REVIEW

**Comment by Zaid-maker** [comment]
Awesome man.

**Review by Zaid-maker — APPROVED** [review]
Looks good and thanks for providing image.

**Comment by Awish-Senpai** [comment]
Ah, sure. I will be contributing more :)

**Comment by Sank6** [comment]
Use css variables so it works with dark mode.

**Comment by tovade** [comment]
sank for me its working in dark mode

**Comment by Sank6** [comment]
Yes it works, but I mean you're manually assigning the colour of the scrollbar. It doesn't have the same colour as the theme. Change the colour to `var(--primary)` so it auto updates the colour of the scrollbar when you change the theme or edit the theme colours.
image

**Pull request merged**
