### PR TITLE
Kick command

### PR DESCRIPTION
**Pull request by idk-pixel**

### CODE REVIEW

**Comment by Sank6** [comment]
Can you put the module imports at the top and change the path for the config file to `@root/config.json`. Also get the prefix directly from the require. Check the other files.

**Comment by Sank6** [comment]
Actually, have a look if you can use this: https://github.com/dirigeants/klasa-pieces/blob/master/commands/Moderation/kick.js

**Comment by idk-pixel** [comment]
@Sank6 fixed btw

**Comment by Sank6** [comment]
Move the imports to the top of the file. Also use Klasa args so the argument is a user.

**Comment by Sank6** [comment]
ty btw. :)

**Pull request closed without merging**
