### PR TITLE
Voting System

### PR DESCRIPTION
**Pull request by shootdot**

### CODE REVIEW

**Review by zarar2312 — APPROVED** [review]

**Comment by Sank6** [comment]
Most of it is really nice. Gj on your first time contribution. I like the way you limited the number of votes per user for a time period, but there's some stuff that needs to be changed. I looked through it and found a few issues:
- You need to add "votes" to `models/bots.js`, with `type: Number` and `default: 0`.
- Your calculating votes in the frontend. Don't do this because a user can just make a request with any number of votes. This is the same with the date. Make the api request be an empty post request. No data is sent. You can get the user from `req.user` and then calculate the time in the backend. Instead of updating the votes with a new number, use MongoDB's `$inc` increment operator. 

And a few smaller things:
 - For `routes/bots/vote.js`, use `auth` middleware like in `routes/theme.js`. Then you don't need to put everything in an if statement. Also you can remove the frontend dealing with whether the user is signed in. It's neater to just redirect to sign in. 
 - In `dynamic/includes/head.pug`, don't import SWAL for all pages. It'll slow down the page loading. Look at how it's imported for the bot edit page. Add an or to the if statement.
 - In `dynamic/bots.pug`, put line 40 back.
 - Also, what's with the svg `dicon.svg`??

Everything else seems good I think. @ me when you've updated it.

**Comment by shootdot** [comment]
Thanks a lot. I will fix the necessary changes and update the branch 👍

**Comment by shootdot** [comment]
@Sank6 I have done the changes as you told but in `dynamic/bots.pug` the line 40  `a.bot-btns.button(target='_blank' href=bot.invite ? bot.invite : `https://discord.com/oauth2/authorize?client_id=${bot.botid}&scope=bot&permissions=0`)` is already there in line 44.

**Comment by ririko5834** [comment]
Is this working 100% now? Can i manually add these changes to my botlist?

**Comment by shootdot** [comment]
Yea you can add this and try if you want. It's working perfectly.

**Comment by Zaid-maker** [comment]
Please make a PR so sank6 can easily see it btw thanks for that.

**Comment by Sank6** [comment]
@shootdot Oh yeah sorry. I didn't see that. I'll test it in a bit. 👍

**Comment by shootdot** [comment]
Yea sure  👍

**Comment by Zaid-maker** [comment]
Awesome work dude.

**Review by Zaid-maker — APPROVED** [review]
Awesome thanks for contributing to the list.

**Comment by shootdot** [comment]
Np 😊

**Comment by ririko5834** [comment]
@shootdot src/routes/api/vote/index.js
```js
const { Router } = require("express");
const { auth } = require("@utils/discordApi");
const Bots = require("@models/bots");
const Users = require("@models/users");
const { server, web } = require("@root/config.json")
const Discord = require("discord.js");

const route = Router();

route.patch("/:id", auth, async (req, res) => {
  let vote = 1
  let date = new Date();
  await Bots.updateOne({ botid: req.params.id }, { $inc: { vote } })
  const users = await Users.findOne({ userid: req.user.id }, { _id: false })
  if (!users) {
    new Users({
      userid: req.user.id,
      date: new Date()
    }).save()
  } else {
    await Users.updateOne({ userid: req.user.id }, { $set: { date } });
  }
  let userProfile = await req.app.get('client').users.fetch(req.user.id);
  let bot = await Bots.findOne({botid: req.params.id}, { _id: false, auth: false });
  const embed = new Discord.MessageEmbed()
    .setTitle('Vote Count Updated! 🎉')
    .setColor('BLUE')
    .setDescription(`The vote count for <@${req.params.id}> has been updated.`)
    .addField(`Voter`, `<@${req.user.id}> (${userProfile.tag})`, false)
    .addField(`Vote Count`, `${bot.vote} Votes`, false)
    .addField(`Bot Page`, `[Here](${web.domain_with_protocol}/bots/${req.params.id})`)
    .setTimestamp();
  const channel = await req.app.get('client').channels.cache.get(server.vote_log);
  const webhooks = await channel.fetchWebhooks();
  const webhook = webhooks.first();
  await webhook.send({
    embeds: [embed],
  });
  return res.json({ success: true })
});

module.exports = route;```

Is this correct code? For me voting using bot command work but voting using web doesnt do anything.

**Comment by shootdot** [comment]
Yes this is the code check browser console if it nothing happens.

**Comment by ririko5834** [comment]
btw where is code for sorting bots by vote count? Vote count is not showed on main page of botlist when browsing bots.

**Comment by shootdot** [comment]
Looks like you haven't copied the whole code. Clone the repo from [Here](https://github.com/shootdot/Discord-Bot-List/tree/patch-1) and fill the config.json file

**Comment by ririko5834** [comment]
Bug: The bots arent sorted by vote count in `/user/:id` and `/me` routes.

**Comment by shootdot** [comment]
Those areas aren't necessary to be sorted.

**Comment by shootdot** [comment]
Bots need not to be sorted in those areas. So it's not a bug.

**Comment by Sank6** [comment]
Everything seems to be working. I might tidy up some parts but ty. 👍

**Comment by Sank6** [comment]
Oh you're still checking for dates in the frontend.

**Comment by shootdot** [comment]
> Oh you're still checking for dates in the frontend.

Yea I was busy today the whole day I will work on it and and create a new PR 😊

**Comment by shootdot** [comment]
By the way update readme.md

**Comment by Sank6** [comment]
Yeah I'm fixing it rn dw

**Comment by shootdot** [comment]
Oh ty

**Pull request merged**
